# Use the official Ubuntu base imagexxx
FROM ubuntu:24.04

# Install CMake, a C++ compiler, Jenkins, and required dependencies
RUN apt-get update && \
    apt-get install -y wget ca-certificates openjdk-21-jdk cmake g++ make && \
    mkdir -p /etc/apt/keyrings && \
    wget -q -O /etc/apt/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key && \
    echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list && \
    apt-get update && \
    apt-get install -y jenkins && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /home/jenkins
